import 'package:dto/models/user.dart';
import 'package:firestore_odm/firestore_odm.dart';

final List<User> users = [
  User(
    firstName: "Ada",
    lastName: "Lovelace",
    email: "ada@example.com",
    id: FirestoreODM.autoGeneratedId,
    createdAt: DateTime.now(),
  ),
  User(
    firstName: "Alan",
    lastName: "Turing",
    email: "alan@example.com",
    id: FirestoreODM.autoGeneratedId,
    createdAt: DateTime.now(),
  ),
  User(
    firstName: "Grace",
    lastName: "Hopper",
    email: "grace@example.com",
    id: FirestoreODM.autoGeneratedId,
    createdAt: DateTime.now(),
  ),
  User(
    firstName: "Linus",
    lastName: "Torvalds",
    email: "linus@example.com",
    id: FirestoreODM.autoGeneratedId,
    createdAt: DateTime.now(),
  ),
  User(
    firstName: "Margaret",
    lastName: "Hamilton",
    email: "margaret@example.com",
    id: FirestoreODM.autoGeneratedId,
    createdAt: DateTime.now(),
  ),
  User(
    firstName: "Tim",
    lastName: "Berners-Lee",
    email: "tim@example.com",
    id: FirestoreODM.autoGeneratedId,
    createdAt: DateTime.now(),
  ),
];
